local opt = vim.opt -- for conciseness

opt.tabstop = 2
opt.shiftwidth = 2
opt.updatetime = 200
opt.fileencoding = "utf-8"
opt.filetype = "on"
opt.clipboard = "unnamedplus"
opt.smartcase = true
opt.ignorecase = true
opt.cursorline = true
opt.smartindent = true
opt.number = true
opt.relativenumber = true
opt.wrap = false
opt.hlsearch = true
opt.showmode = false
opt.swapfile = false
opt.signcolumn = "yes"
opt.termguicolors = true
