import = [
	"/home/rlggyp/.config/alacritty/tokyo-night.toml"
]

[shell]
program = "/bin/zsh"

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 7

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[window]
opacity = 1.0
dynamic_padding = true

[window.dimensions]
columns = 175
lines = 40

[window.padding]
x = 2
y = 2
