[colors.primary]
background = "#1A1B26"
foreground = "#C0CAF5"
dim_foreground = "#CDD6F4"
bright_foreground = "#CDD6F4"

[colors.cursor]
text = "#1A1B26"
cursor = "#C0CAF5"

[colors.vi_mode_cursor]
text = "#1A1B26"
cursor = "#C0CAF5"

[colors.search.matches]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.search.focused_match]
foreground = "#1E1E2E"
background = "#A6E3A1"

[colors.footer_bar]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.hints.start]
foreground = "#1E1E2E"
background = "#F9E2AF"

[colors.hints.end]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.selection]
text = "#C0CAF5"
background = "#33467C"

[colors.normal]
black = "#15161E"
red = "#F7768E"
green = "#9ECE6A"
yellow = "#E0AF68"
blue = "#7AA2F7"
magenta = "#BB9AF7"
cyan = "#7DCFFF"
white = "#A9B1D6"

[colors.bright]
black = "#414868"
red = "#F7768E"
green = "#9ECE6A"
yellow = "#E0AF68"
blue = "#7AA2F7"
magenta = "#BB9AF7"
cyan = "#7DCFFF"
white = "#C0CAF5"

# [colors.dim]
# black = "#45475A"
# red = "#F38BA8"
# green = "#A6E3A1"
# yellow = "#F9E2AF"
# blue = "#89B4FA"
# magenta = "#F5C2E7"
# cyan = "#94E2D5"
# white = "#BAC2DE"

[[colors.indexed_colors]]
index = 16
color = "#FF9E64"

[[colors.indexed_colors]]
index = 17
color = "#DB4B4B"
